### ISSUE TITLE
Question: Do I need to zip Java lambda in form of JAR file?

### ISSUE THREAD

**Issue by archenroot** [crisboarna/terraform-aws-api-gateway-lambda-dynamodb#3]
it seems lambda module is prepared for zip file, do I need to zip packaged java lambda in form of jar (which is actually a zip archive) again?

**Comment by crisboarna** [comment]
If you are referring to `defaultLambadFile.zip` snipper in the lambda module, it is used as default value for case where you are using S3 path for artifact. module makes no assumptions on whether it is jar or zip. For Lambda to work with JVM Jar you will need to simply point it to the .jar file.
